// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

type Feed struct {
	ID     int64
	UserID int64
	Url    string
	Title  string
}

type UserSetting struct {
	UserID            int64
	AutoDigestHourUtc int64
}
