// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sql

import (
	"context"
)

const addOrIgnoreFeed = `-- name: AddOrIgnoreFeed :exec
insert or ignore into
    feeds (user_id, url, title)
values
    (?, ?, ?)
`

type AddOrIgnoreFeedParams struct {
	UserID int64
	Url    string
	Title  string
}

func (q *Queries) AddOrIgnoreFeed(ctx context.Context, arg AddOrIgnoreFeedParams) error {
	_, err := q.db.ExecContext(ctx, addOrIgnoreFeed, arg.UserID, arg.Url, arg.Title)
	return err
}

const getHourFeeds = `-- name: GetHourFeeds :many
select
    f.id,
    f.user_id,
    f.url,
    f.title
from
    feeds as f
    left join user_settings as us on us.user_id = f.user_id
where
    us.auto_digest_hour_utc = ?
`

func (q *Queries) GetHourFeeds(ctx context.Context, autoDigestHourUtc int64) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getHourFeeds, autoDigestHourUtc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHourFeedsMidnightUTC = `-- name: GetHourFeedsMidnightUTC :many
select
    f.id,
    f.user_id,
    f.url,
    f.title
from
    feeds as f
    left join user_settings as us on us.user_id = f.user_id
where
    us.user_id is null
    or us.auto_digest_hour_utc = ?
`

func (q *Queries) GetHourFeedsMidnightUTC(ctx context.Context, autoDigestHourUtc int64) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getHourFeedsMidnightUTC, autoDigestHourUtc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFeeds = `-- name: GetUserFeeds :many
select
    id,
    url,
    title
from
    feeds
where
    user_id = ?
`

type GetUserFeedsRow struct {
	ID    int64
	Url   string
	Title string
}

func (q *Queries) GetUserFeeds(ctx context.Context, userID int64) ([]GetUserFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFeedsRow
	for rows.Next() {
		var i GetUserFeedsRow
		if err := rows.Scan(&i.ID, &i.Url, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSettings = `-- name: GetUserSettings :one
select
    user_id,
    auto_digest_hour_utc
from
    user_settings
where
    user_id = ?
`

func (q *Queries) GetUserSettings(ctx context.Context, userID int64) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(&i.UserID, &i.AutoDigestHourUtc)
	return i, err
}

const removeFeed = `-- name: RemoveFeed :exec
delete from feeds
where
    id = ?
`

func (q *Queries) RemoveFeed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeFeed, id)
	return err
}

const updateFeedTitle = `-- name: UpdateFeedTitle :exec
update feeds
set
    title = ?
where
    id = ?
`

type UpdateFeedTitleParams struct {
	Title string
	ID    int64
}

func (q *Queries) UpdateFeedTitle(ctx context.Context, arg UpdateFeedTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedTitle, arg.Title, arg.ID)
	return err
}

const upsertUserSettings = `-- name: UpsertUserSettings :exec
insert into
    user_settings (user_id, auto_digest_hour_utc)
values
    (?, ?)
on conflict (user_id) do update
set
    auto_digest_hour_utc = excluded.auto_digest_hour_utc
`

type UpsertUserSettingsParams struct {
	UserID            int64
	AutoDigestHourUtc int64
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserSettings, arg.UserID, arg.AutoDigestHourUtc)
	return err
}
