version: "2"

linters:
  enable:
    - lll
    - dupl
    - nlreturn
    - importas
    - goconst
    - errorlint

  settings:
    lll:
      line-length: 80

    importas:
      alias:
        - pkg: github.com/go-telegram-bot-api/telegram-bot-api/v5
          alias: tgbotapi

formatters:
  enable:
    - golines
    - goimports

  settings:
    golines:
      max-len: 80
      tab-len: 1
      shorten-comments: true

    goimports:
      local-prefixes:
        - telekilogram
