name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v9

  vulncheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.mod

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: make test
      - uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
    needs: [lint, vulncheck, test]
    uses: hu553in/common-things/.github/workflows/build-publish-docker.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      image: ghcr.io/${{ github.repository }}
